module.exports = {
	parser: '@typescript-eslint/parser',
	plugins: [
		'@typescript-eslint',
		'implicit-dependencies',
		'import',
	],
	env: {
		es2020: true,
		node: true,
	},
	ignorePatterns: [
		'node_modules/',
		'dist/',
		'dist.browser/',
		'coverage/',
		'prettier.config.cjs',
		'typedoc.js',
		'docs',
		'.eslintrc.cjs',
		'vitest.config.*.ts',
		'archived-browser-client/',
		'browser-client/',
		'ui/',
		'scripts/',
		'proxy/'
	],
	extends: [
		'typestrict',
		'eslint:recommended',
		'plugin:import/recommended',
		'plugin:import/typescript',
	],
	rules: {
		'no-restricted-imports': ['error', 'ethereum-cryptography/utils.js'],
		'@typescript-eslint/consistent-type-imports': 'error',
		'@typescript-eslint/no-use-before-define': 'error',
		'@typescript-eslint/naming-convention': [
			'error',
			{
				selector: 'interface',
				format: ['PascalCase', 'camelCase'],
			},
		],
		'@typescript-eslint/no-unused-vars': [
			'error',
			{ argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
		],
		'@typescript-eslint/no-redeclare': ['error'],
		'@typescript-eslint/no-unnecessary-condition': 'off',
		'@typescript-eslint/prefer-nullish-coalescing': 'error',
		'@typescript-eslint/restrict-plus-operands': 'off',
		'@typescript-eslint/return-await': 'error',
		'@typescript-eslint/strict-boolean-expressions': ['error'],
		eqeqeq: 'error',
		'implicit-dependencies/no-implicit': ['error', { peer: true, dev: true, optional: true }],
		'import/default': 'error',
		'import/export': 'error',
		'import/exports-last': 'off', // TODO: set to `warn` for fixing and then `error`
		'import/extensions': ['error', 'ignorePackages'],
		'import/first': 'error',
		'import/group-exports': 'off',
		'import/named': 'error',
		'import/namespace': 'error',
		'import/no-absolute-path': 'error',
		'import/no-anonymous-default-export': 'error',
		'import/no-cycle': 'off', // TODO: set to `warn` for fixing and then `error`
		'import/no-default-export': ['error'],
		'import/no-deprecated': 'off', // TODO: set to `warn` for fixing and then `error`
		'import/no-duplicates': 'error',
		'import/no-dynamic-require': 'off',
		'import/no-extraneous-dependencies': 'error',
		'import/no-mutable-exports': 'error',
		'import/no-namespace': 'off',
		'import/no-self-import': 'error',
		'import/no-unresolved': 'off',
		'import/no-unused-modules': 'error',
		'import/no-useless-path-segments': 'error',
		'import/no-webpack-loader-syntax': 'error',
		'no-console': 'warn',
		'no-debugger': 'error',
		'no-dupe-class-members': 'off',
		'no-redeclare': 'off',
		'no-unused-vars': 'off',
		'no-var': 'error',
		'object-shorthand': 'error',
		'prefer-const': 'error',
		'sort-imports': ['error', { ignoreDeclarationSort: true }],
	},
	parserOptions: {
		extraFileExtensions: ['.json'],
		sourceType: 'module',
		project: './config/tsconfig.lint.json',
	},
	overrides: [
		{
		  files: ['**/cli/**/*.ts'],
		  rules: {
			'no-console': 'off',
		  },
		},
	]
}
